SIGNO_PREGUNTA = "?"

MENSAJE_INICIAL = "Palabra a adivinar"
MENSAJE_ACIERTO = "Muy bien!!!"
MENSAJE_DESACIERTO = "Lo siento!!!"
MENSAJE_LETRA_INGRESADA = "Letra ya ingresada"
MENSAJE_INGRESO_INVALIDO = "Ingreso inválido"
MENSAJE_DESPEDIDA = "Hasta luego!"
MENSAJE_INPUT_LETRA = "Ingrese letra: "

LETRAS_FIN = ["FIN", "0"]

LONGITUD_MINIMA_PALABRA = 5
INDICE_CLAVE = 0